public class DB_SyncUMP { public DB_DataSourceDetail DB_DataSourceDetail { get; set; } public DB_ServerVersion DB_ServerVersion { get; set; } public DB_User DB_User { get; set; } public DB_Group DB_Group { get; set; } public DB_UserGroup DB_UserGroup { get; set; } public DB_UserLogType DB_UserLogType { get; set; } public DB_UserLog DB_UserLog { get; set; } public DB_UserLogin DB_UserLogin { get; set; } public DB_UserPreference DB_UserPreference { get; set; } public DB_SystemLogType DB_SystemLogType { get; set; } public DB_SystemLog DB_SystemLog { get; set; } public DB_ItemType DB_ItemType { get; set; } public DB_Item DB_Item { get; set; } public DB_ItemLogType DB_ItemLogType { get; set; } public DB_ItemTrash DB_ItemTrash { get; set; } public DB_ItemTrashDeleted DB_ItemTrashDeleted { get; set; } public DB_ItemVersion DB_ItemVersion { get; set; } public DB_ItemLog DB_ItemLog { get; set; } public DB_PermissionEntity DB_PermissionEntity { get; set; } public DB_UserPermission DB_UserPermission { get; set; } public DB_GroupPermission DB_GroupPermission { get; set; } public DB_RecurrenceType DB_RecurrenceType { get; set; } public DB_ExportType DB_ExportType { get; set; } public DB_ScheduleDetail DB_ScheduleDetail { get; set; } public DB_SubscribedUser DB_SubscribedUser { get; set; } public DB_SubscribedGroup DB_SubscribedGroup { get; set; } public DB_ScheduleStatus DB_ScheduleStatus { get; set; } public DB_ScheduleLogUser DB_ScheduleLogUser { get; set; } public DB_ScheduleLogGroup DB_ScheduleLogGroup { get; set; } public DB_ReportDataSource DB_ReportDataSource { get; set; } public DB_ScheduleLog DB_ScheduleLog { get; set; } public DB_SystemSettings DB_SystemSettings { get; set; } }
public class DB_DataSourceDetail { public string DB_TableName { get; set; } public string Id { get; set; } public string DataSourceId { get; set; } public string Password { get; set; } public string ModifiedDate { get; set; } public string IsActive { get; set; } }
public class DB_ServerVersion { public string DB_TableName { get; set; } public string VersionNumber { get; set; } }
public class DB_User { public string DB_TableName { get; set; } public string Id { get; set; } public string UserName { get; set; } public string FirstName { get; set; } public string LastName { get; set; } public string DisplayName { get; set; } public string Email { get; set; } public string Password { get; set; } public string Contact { get; set; } public string Picture { get; set; } public string CreatedDate { get; set; } public string ModifiedDate { get; set; } public string LastLogin { get; set; } public string ActivationExpirationDate { get; set; } public string ActivationCode { get; set; } public string ResetPasswordCode { get; set; } public string LastResetAttempt { get; set; } public string IsActivated { get; set; } public string IsActive { get; set; } public string IsDeleted { get; set; } }
public class DB_Group { public string DB_TableName { get; set; } public string Id { get; set; } public string Name { get; set; } public string Description { get; set; } public string Color { get; set; } public string ModifiedDate { get; set; } public string IsActive { get; set; } }
public class DB_UserGroup { public string DB_TableName { get; set; } public string Id { get; set; } public string GroupId { get; set; } public string UserId { get; set; } public string ModifiedDate { get; set; } public string IsActive { get; set; } }
public class DB_UserLogType { public string DB_TableName { get; set; } public string Id { get; set; } public string Name { get; set; } public string IsActive { get; set; } }
public class DB_UserLog { public string DB_TableName { get; set; } public string Id { get; set; } public string UserLogTypeId { get; set; } public string GroupId { get; set; } public string OldValue { get; set; } public string NewValue { get; set; } public string UpdatedUserId { get; set; } public string TargetUserId { get; set; } public string ModifiedDate { get; set; } public string IsActive { get; set; } }
public class DB_UserLogin { public string DB_TableName { get; set; } public string Id { get; set; } public string UserId { get; set; } public string ClientToken { get; set; } public string IpAddress { get; set; } public string LoggedInTime { get; set; } public string IsActive { get; set; } }
public class DB_UserPreference { public string DB_TableName { get; set; } public string Id { get; set; } public string UserId { get; set; } public string Language { get; set; } public string TimeZone { get; set; } public string RecordSize { get; set; } public string ItemSort { get; set; } public string ItemFilters { get; set; } public string ModifiedDate { get; set; } public string IsActive { get; set; } }
public class DB_SystemLogType { public string DB_TableName { get; set; } public string Id { get; set; } public string Name { get; set; } public string IsActive { get; set; } }
public class DB_SystemLog { public string DB_TableName { get; set; } public string LogId { get; set; } public string SystemLogTypeId { get; set; } public string UpdatedUserId { get; set; } public string TargetUserId { get; set; } public string ModifiedDate { get; set; } public string IsActive { get; set; } }
public class DB_ItemType { public string DB_TableName { get; set; } public string Id { get; set; } public string Name { get; set; } public string IsActive { get; set; } }
public class DB_Item { public string DB_TableName { get; set; } public string Id { get; set; } public string Name { get; set; } public string Description { get; set; } public string ItemTypeId { get; set; } public string ParentId { get; set; } public string Extension { get; set; } public string CloneItemId { get; set; } public string CreatedById { get; set; } public string ModifiedById { get; set; } public string CreatedDate { get; set; } public string ModifiedDate { get; set; } public string IsActive { get; set; } }
public class DB_ItemLogType { public string DB_TableName { get; set; } public string Id { get; set; } public string Name { get; set; } public string IsActive { get; set; } }
public class DB_ItemTrash { public string DB_TableName { get; set; } public string Id { get; set; } public string ItemId { get; set; } public string TrashedById { get; set; } public string TrashedDate { get; set; } public string IsActive { get; set; } }
public class DB_ItemTrashDeleted { public string DB_TableName { get; set; } public string Id { get; set; } public string ItemId { get; set; } public string ItemTrashId { get; set; } public string DeletedById { get; set; } public string DeletedDate { get; set; } public string IsActive { get; set; } }
public class DB_ItemVersion { public string DB_TableName { get; set; } public string Id { get; set; } public string ItemId { get; set; } public string ItemTypeId { get; set; } public string ItemName { get; set; } public string VersionNumber { get; set; } public string RolledbackVersionNumber { get; set; } public string Comment { get; set; } public string IsCurrentVersion { get; set; } public string CreatedById { get; set; } public string CreatedDate { get; set; } public string IsActive { get; set; } }
public class DB_ItemLog { public string DB_TableName { get; set; } public string Id { get; set; } public string ItemLogTypeId { get; set; } public string ItemId { get; set; } public string ItemVersionId { get; set; } public string ParentId { get; set; } public string FromCategoryId { get; set; } public string ToCategoryId { get; set; } public string UpdatedUserId { get; set; } public string ModifiedDate { get; set; } public string IsActive { get; set; } }
public class DB_PermissionEntity { public string DB_TableName { get; set; } public string Id { get; set; } public string Name { get; set; } public string EntityType { get; set; } public string IsActive { get; set; } }
public class DB_UserPermission { public string DB_TableName { get; set; } public string Id { get; set; } public string PermissionAccessId { get; set; } public string PermissionEntityId { get; set; } public string ItemId { get; set; } public string UserId { get; set; } public string IsActive { get; set; } }
public class DB_GroupPermission { public string DB_TableName { get; set; } public string Id { get; set; } public string PermissionAccessId { get; set; } public string PermissionEntityId { get; set; } public string ItemId { get; set; } public string GroupId { get; set; } public string IsActive { get; set; } }
public class DB_RecurrenceType { public string DB_TableName { get; set; } public string Id { get; set; } public string Name { get; set; } public string IsActive { get; set; } }
public class DB_ExportType { public string DB_TableName { get; set; } public string Id { get; set; } public string Name { get; set; } public string IsActive { get; set; } }
public class DB_ScheduleDetail { public string DB_TableName { get; set; } public string Id { get; set; } public string ScheduleId { get; set; } public string ItemId { get; set; } public string Name { get; set; } public string RecurrenceTypeId { get; set; } public string RecurrenceInfo { get; set; } public string StartDate { get; set; } public string EndDate { get; set; } public string EndAfter { get; set; } public string NextSchedule { get; set; } public string ExportTypeId { get; set; } public string IsEnabled { get; set; } public string CreatedById { get; set; } public string ModifiedById { get; set; } public string CreatedDate { get; set; } public string ModifiedDate { get; set; } public string IsActive { get; set; } }
public class DB_SubscribedUser { public string DB_TableName { get; set; } public string Id { get; set; } public string ScheduleId { get; set; } public string SubscribedById { get; set; } public string RecipientUserId { get; set; } public string SubscribedDate { get; set; } public string ModifiedDate { get; set; } public string IsActive { get; set; } }
public class DB_SubscribedGroup { public string DB_TableName { get; set; } public string Id { get; set; } public string ScheduleId { get; set; } public string SubscribedById { get; set; } public string RecipientGroupId { get; set; } public string SubscribedDate { get; set; } public string ModifiedDate { get; set; } public string IsActive { get; set; } }
public class DB_ScheduleStatus { public string DB_TableName { get; set; } public string Id { get; set; } public string Name { get; set; } public string IsActive { get; set; } }
public class DB_ScheduleLogUser { public string DB_TableName { get; set; } public string Id { get; set; } public string ScheduleId { get; set; } public string ScheduleStatusId { get; set; } public string DeliveredUserId { get; set; } public string DeliveredDate { get; set; } public string IsOnDemand { get; set; } public string IsActive { get; set; } }
public class DB_ScheduleLogGroup { public string DB_TableName { get; set; } public string Id { get; set; } public string ScheduleId { get; set; } public string ScheduleStatusId { get; set; } public string GroupId { get; set; } public string DeliveredUserId { get; set; } public string DeliveredDate { get; set; } public string IsOnDemand { get; set; } public string IsActive { get; set; } }
public class DB_ReportDataSource { public string DB_TableName { get; set; } public string Id { get; set; } public string ReportItemId { get; set; } public string DataSourceItemId { get; set; } public string Name { get; set; } public string ModifiedDate { get; set; } public string IsActive { get; set; } }
public class DB_ScheduleLog { public string DB_TableName { get; set; } public string Id { get; set; } public string ScheduleStatusId { get; set; } public string ScheduleId { get; set; } public string ExecutedDate { get; set; } public string ModifiedDate { get; set; } public string IsOnDemand { get; set; } public string IsActive { get; set; } }
public class DB_SystemSettings { public string DB_TableName { get; set; } public string Id { get; set; } public string Key { get; set; } public string Value { get; set; } public string IsActive { get; set; } }